server:
  port: 8085
spring:
  application:
      name: SdcSoft_CloudCenter_PlcDataInput
  rabbitmq:
    host: 39.106.168.77
    port: 5672
    username: tomcat
    password: 80201288
    virtualhost: MsgCenter
    template:
      exchange: DeviceMsgExchange
      routing-key: ByteDeviceMsg
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
